#!/usr/bin/env python3
"""#91 codegen: skeleton fixtures and expected-output files.

The only Python anywhere in the standalone-skeleton slice, and it runs at
fixture-creation time, never at check time. Three outputs:

1. ``crates/mypy-rs-skel/fixtures/skeleton_fixtures.json``: the
   checking-phase typeinfo read-closure of the grown corpus (8 records
   for the trivial corpus, #85; 13 stdlib records for the class/member
   slice, #118 probe #114), snapshotted with exactly the read
   vocabulary the kernel's ``snapshot_type_info`` uses
   (crates/type_kernel/src/typeinfo.rs). Wire-format Type blobs are
   emitted as lowercase hex; the skeleton decodes them into
   ``TypeInfoSnapshot`` records consumed by ``is_subtype``. The four
   corpus classes are asserted present but never dumped: the skeleton
   builds their models and snapshots itself at check time. The
   producer-owned records (#151, PRODUCER_OWNED below) are dumped here
   *and* into the producer golden: the Rust producer
   (``crates/mypy-rs-skel/src/port/stubs.rs``) is not wired into the
   driver yet, so the fixture path still serves those records at check
   time, and the golden is the ground truth its differential is proved
   against. Dropping the fixture half is wave-2 work (the driver has to
   read the producer first); until then the freshness gate below holds
   both files in step, so neither can drift.

2. ``crates/mypy-rs-skel/testdata/producer_golden.json``: the codegen
   records for the producer-owned fullnames (#151), the ground truth
   the producer's differential test compares against. Regenerated here
   from the same live mypy build; the producer never writes it.

3. ``crates/mypy-rs-skel/testdata/*.expected``: byte-exact expected
   stdout of real mypy on the corpus (the gate 1 arms plus every
   supported manifest arm, #115), regenerated by invoking the tree's
   own ``python -m mypy`` as a subprocess with cwd=testdata so the
   recorded paths match the differential harness invocation. The
   manifest's declared exit codes are validated against the real run.

All outputs are deterministic (sorted keys, no timestamps). ``--check``
regenerates into a scratch directory and exits 1 when the committed files
differ, for the CI freshness gate.

Usage:
  .venv/bin/python misc/skeleton_codegen.py [--check]
Prereq: the native extension scratch dirs (AGENTS.md native build
order) on PYTHONPATH, or named in MYPY_RS_EXT_DIRS (os.pathsep
list); the in-process build runs the default-on native seams and
the native parser needs the in-repo extension.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile

TAG = "[skeleton-codegen]"

# The #118 probe closure (#114) plus builtins.int / builtins.bool,
# closing the int/bool literal promote path (review H5) so
# `f: float = 1` decides; corpus records stay out (skeleton-owned).
CLOSURE = [
    "abc.ABCMeta",
    "builtins.bool",
    "builtins.float",
    "builtins.function",
    "builtins.int",
    "builtins.object",
    "builtins.str",
    "builtins.type",
    "class_slice.Circle",
    "class_slice.NamedBox",
    "class_slice_base.Shape",
    "class_slice_base.Sized",
    "typing.Collection",
    "typing.Container",
    "typing.Iterable",
    "typing.Reversible",
    "typing.Sequence",
]

# Modules the skeleton checks itself; their records stay out of the dump.
CORPUS_MODULES = frozenset({"class_slice", "class_slice_base", "control_flow"})

# Fullnames the Rust stub producer owns (#151): its records go to
# testdata/producer_golden.json as the differential's ground truth, and
# stay in the fixtures until the driver reads the producer (wave 2).
PRODUCER_OWNED = [
    "builtins.bool",
    "builtins.float",
    "builtins.function",
    "builtins.int",
    "builtins.object",
    "builtins.str",
    "builtins.type",
]

# Corpus classes each checked module must define (sanity guard).
CORPUS_CLASSES = {
    "class_slice": ("Circle", "NamedBox"),
    "class_slice_base": ("Shape", "Sized"),
    "control_flow": (),
}

# Primitive names the semanal subset resolves annotations through.
PRIMITIVE_NAMES = ["bool", "float", "int", "str"]

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKEL_DIR = os.path.join(REPO_ROOT, "crates", "mypy-rs-skel")
FIXTURE_PATH = os.path.join(SKEL_DIR, "fixtures", "skeleton_fixtures.json")
TESTDATA_DIR = os.path.join(SKEL_DIR, "testdata")
MANIFEST_PATH = os.path.join(TESTDATA_DIR, "manifest.json")
# Where the producer-owned codegen records land (#151).
GOLDEN_PATH = os.path.join(TESTDATA_DIR, "producer_golden.json")


def pin_this_tree() -> None:
    """Worktree prelude (#1789): the shared .venv's editable finder may
    map `mypy` to another (possibly deleted) tree, and sys.path[0] is
    misc/, not the root. Pin this tree before importing mypy, and put
    the native extension dirs on sys.path: the in-process build runs
    the default-on native seams (ast_serialize et al.)."""
    if REPO_ROOT not in sys.path:
        sys.path.insert(0, REPO_ROOT)
    for finder in list(sys.meta_path):
        if "editable" in (type(finder).__module__ or "") or "editable" in repr(finder):
            sys.meta_path.remove(finder)
    for d in extension_dirs():
        if d not in sys.path:
            sys.path.insert(1, d)


def blob_hex(writer: object, buf_cls: object) -> str:
    buf = buf_cls()
    writer.write(buf)
    return bytes(buf.getvalue()).hex()


def snapshot_type_info(info: object, buf_cls: object) -> dict:
    """Mirror of ``snapshot_type_info`` (typeinfo.rs:1321-1399): the same
    attributes, the same defaults on missing/None, the same skips. Any
    divergence here is a fixture bug that the differential surfaces."""
    fullname = info.fullname
    d: dict = {}
    d["fullname"] = fullname
    d["name"] = getattr(info, "name", None) or fullname.rsplit(".", 1)[-1]
    d["is_protocol"] = bool(getattr(info, "is_protocol", False))
    d["is_enum"] = bool(getattr(info, "is_enum", False))
    enum_members = getattr(info, "enum_members", None)
    d["enum_members"] = [str(x) for x in enum_members] if enum_members else []
    d["fallback_to_any"] = bool(getattr(info, "fallback_to_any", False))
    d["meta_fallback_to_any"] = bool(getattr(info, "meta_fallback_to_any", False))
    d["is_named_tuple"] = bool(getattr(info, "is_named_tuple", False))
    d["is_newtype"] = bool(getattr(info, "is_newtype", False))
    d["has_type_var_tuple_type"] = bool(getattr(info, "has_type_var_tuple_type", False))
    d["has_param_spec_type"] = bool(getattr(info, "has_param_spec_type", False))
    d["is_abstract"] = bool(getattr(info, "is_abstract", False))
    type_vars = getattr(info, "type_vars", None)
    d["type_vars"] = [str(x) for x in type_vars] if type_vars else []
    mro = getattr(info, "mro", None)
    d["mro"] = [t.fullname for t in mro] if mro else []
    protocol_members = getattr(info, "protocol_members", None)
    d["protocol_members"] = [str(x) for x in protocol_members] if protocol_members else []
    promote = getattr(info, "_promote", None)
    d["promote_bytes"] = (
        [blob_hex(t, buf_cls) for t in promote] if isinstance(promote, list) else []
    )
    alt = getattr(info, "alt_promote", None)
    d["alt_promote_fullname"] = alt.type.fullname if alt is not None else None
    metaclass = getattr(info, "metaclass_type", "UNREADABLE")
    if metaclass == "UNREADABLE":
        d["metaclass_fullname"] = None
    elif metaclass is None:
        d["metaclass_fullname"] = ""
    else:
        d["metaclass_fullname"] = metaclass.type.fullname
    bases = getattr(info, "bases", None)
    d["bases"] = [blob_hex(b, buf_cls) for b in bases] if isinstance(bases, list) else []
    tuple_type = getattr(info, "tuple_type", None)
    d["tuple_type"] = blob_hex(tuple_type, buf_cls) if tuple_type is not None else None
    d["type_var_tuple_prefix"] = getattr(info, "type_var_tuple_prefix", None)
    d["type_var_tuple_suffix"] = getattr(info, "type_var_tuple_suffix", None)
    defn = getattr(info, "defn", None)
    defn_tvars = list(defn.type_vars) if defn is not None else []
    fallback = None
    triples = []
    upper_bounds = []
    raw_ids = []
    for tvar in defn_tvars:
        # Positional, one entry per tvar: the kernel's
        # read_type_var_raw_ids never skips, even when the name is
        # unreadable (nameless tvars skip only the variance triples).
        tv_id = getattr(tvar, "id", None)
        raw_ids.append(int(getattr(tv_id, "raw_id", -1)) if tv_id is not None else -1)
        name = getattr(tvar, "name", None)
        if name is None:
            continue
        cls = type(tvar).__name__
        if cls == "TypeVarType":
            variance = int(getattr(tvar, "variance", 0))
            kind = 0
        elif cls == "ParamSpecType":
            variance, kind = 0, 1
        elif cls == "TypeVarTupleType":
            variance, kind = 0, 2
            if fallback is None:
                fallback = blob_hex(tvar.tuple_fallback, buf_cls)
        else:
            variance, kind = 0, 0
        triples.append([str(name), variance, kind])
        if kind == 0:
            bound = getattr(tvar, "upper_bound", None)
            upper_bounds.append(blob_hex(bound, buf_cls) if bound is not None else "")
        else:
            upper_bounds.append("")
    d["type_vars_with_variance"] = triples
    d["type_var_upper_bounds"] = upper_bounds
    d["type_var_raw_ids"] = raw_ids
    d["type_var_tuple_fallback"] = fallback
    names = getattr(info, "names", None)
    member_info = {}
    member_definers = {}
    if names is not None:
        for name, node in names.items():
            implicit = bool(getattr(node, "implicit", False))
            has_explicit = bool(getattr(getattr(node, "node", None), "has_explicit_value", False))
            member_info[str(name)] = [implicit, has_explicit]
            inner = getattr(node, "node", None)
            kind = {"FuncDef": 0, "OverloadedFuncDef": 0, "Decorator": 1, "Var": 2}.get(
                type(inner).__name__, -1
            )
            if kind >= 0:
                definer = getattr(getattr(inner, "info", None), "fullname", "")
                member_definers[str(name)] = [kind, definer]
    d["member_info"] = member_info
    d["member_definers"] = member_definers
    return d


def build_corpus() -> tuple[object, list[str]]:
    """One in-process mypy build of the grown corpus (trivial, the
    class/member slice and the conditional control-flow slice); returns
    the BuildManager holding the live graph the snapshots read."""
    import mypy.build
    from mypy.options import Options

    options = Options()
    options.no_incremental = True
    options.cache_dir = os.path.join(tempfile.mkdtemp(prefix="mypy-rs-skel-codegen-"), "cache")
    sources = [
        mypy.build.BuildSource(os.path.join(TESTDATA_DIR, "trivial.py"), "__main__", None),
        mypy.build.BuildSource(
            os.path.join(TESTDATA_DIR, "class_slice_base.py"), "class_slice_base", None
        ),
        mypy.build.BuildSource(os.path.join(TESTDATA_DIR, "class_slice.py"), "class_slice", None),
        mypy.build.BuildSource(
            os.path.join(TESTDATA_DIR, "control_flow.py"), "control_flow", None
        ),
    ]
    collected: list[str] = []
    result = mypy.build.build(
        sources, options, flush_errors=lambda path, errors, serious: collected.extend(errors)
    )
    return result.manager, collected


def dump_fixtures(manager: object, buf_cls: object) -> tuple[dict, dict]:
    """Returns (fixture file, producer golden). The fixture file keeps
    every record the checker cannot derive at check time, so the driver
    keeps working while the Rust producer is not wired into it; the
    golden carries the producer-owned subset (#151), sorted by fullname
    so the golden is order-stable."""
    records = []
    golden = []
    for fullname in CLOSURE:
        module_name, _, name = fullname.rpartition(".")
        symbol = manager.modules[module_name].names[name]
        info = symbol.node
        assert info.fullname == fullname, (info.fullname, fullname)
        if module_name in CORPUS_MODULES:
            continue
        record = snapshot_type_info(info, buf_cls)
        records.append(record)
        if fullname in PRODUCER_OWNED:
            golden.append(record)
    golden.sort(key=lambda r: r["fullname"])
    builtins_file = manager.modules["builtins"]
    primitives = {}
    for name in PRIMITIVE_NAMES:
        node = builtins_file.names[name].node
        primitives[name] = node.fullname
    return {"builtins_symbols": primitives, "typeinfos": records}, {"typeinfos": golden}


def extension_dirs() -> list[str]:
    """Extension scratch dirs for the regen subprocess. Default is the
    local trio (AGENTS.md native build order); CI overrides via
    MYPY_RS_EXT_DIRS, where the restored cache holds all three."""
    override = os.environ.get("MYPY_RS_EXT_DIRS")
    dirs = (
        override.split(os.pathsep)
        if override
        else [
            "/private/tmp/mypy-rs-local-ast",
            "/private/tmp/mypy-rs-local-resolver",
            "/private/tmp/mypy-rs-local-typekernel",
        ]
    )
    missing = [p for p in dirs if not os.path.isdir(p)]
    if missing:
        print(f"{TAG} warning: missing extension dir(s): {missing}", file=sys.stderr)
    return [p for p in dirs if os.path.isdir(p)]


def supported_arms() -> list[dict]:
    """The manifest's supported entries (#115): this script owns each
    arm's .expected file and validates its declared exit_code against
    the real mypy run, so the committed manifest cannot drift."""
    with open(MANIFEST_PATH, encoding="utf-8") as f:
        manifest = json.load(f)
    entries = [c for c in manifest["capabilities"] if c["status"] == "supported"]
    seen: set[str] = set()
    for entry in entries:
        stem, ext = os.path.splitext(entry["arm"])
        if ext != ".py":
            raise RuntimeError(f"supported arm {entry['id']} is not a .py: {entry['arm']}")
        if stem in seen:
            raise RuntimeError(f"duplicate supported arm: {entry['arm']}")
        seen.add(stem)
    return entries


def regen_expected(scratch: str) -> dict[str, bytes]:
    """Real mypy, subprocess, cwd=testdata, relative arg: the exact
    invocation shape the differential harness uses, so the recorded
    paths and bytes are stable. PYTHONPATH pins this tree plus the
    native extension scratch dirs (AGENTS.md native build order),
    because sys.path[0] for `-m` is the testdata cwd, not the repo.

    A probe subprocess resolves `mypy.__file__` under the same env and
    cwd and must land inside this tree, mirroring the in-process check
    in main(), so a bypassed PYTHONPATH pin cannot feed golden bytes
    from a foreign tree into the committed .expected files."""
    extensions = extension_dirs()
    env = os.environ.copy()
    parts = [p for p in [REPO_ROOT, *extensions] if os.path.isdir(p)]
    existing = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = os.pathsep.join(parts + ([existing] if existing else []))
    probe = subprocess.run(
        [sys.executable, "-c", "import mypy; print(mypy.__file__)"],
        cwd=TESTDATA_DIR,
        env=env,
        capture_output=True,
        text=True,
    )
    resolved = os.path.abspath(probe.stdout.strip())
    if probe.returncode != 0 or not resolved.startswith(REPO_ROOT + os.sep):
        raise RuntimeError(
            f"regen subprocess resolves mypy outside this tree: {resolved} "
            f"(returncode {probe.returncode}, stderr {probe.stderr!r})"
        )
    outputs = {}
    exit_codes = {}
    arms = {"trivial", "empty_control", "class_slice"} | {
        os.path.splitext(e["arm"])[0] for e in supported_arms()
    }
    cache = os.path.join(scratch, "cache")
    for stem in sorted(arms):
        proc = subprocess.run(
            [sys.executable, "-m", "mypy", "--no-incremental", "--cache-dir", cache, f"{stem}.py"],
            cwd=TESTDATA_DIR,
            env=env,
            capture_output=True,
        )
        if proc.stderr:
            raise RuntimeError(f"mypy wrote to stderr for {stem}.py: {proc.stderr!r}")
        if stem == "class_slice" and (proc.returncode != 0 or b"Success" not in proc.stdout):
            raise RuntimeError(
                f"real mypy rejects the class corpus; refusing to record it as golden: "
                f"returncode {proc.returncode}, stdout {proc.stdout!r}"
            )
        outputs[f"{stem}.expected"] = proc.stdout
        exit_codes[stem] = proc.returncode
    for entry in supported_arms():
        stem = os.path.splitext(entry["arm"])[0]
        declared = entry["exit_code"]
        if exit_codes[stem] != declared:
            raise RuntimeError(
                f"manifest exit_code for {entry['id']} ({entry['arm']}) is {declared}, "
                f"real mypy exited {exit_codes[stem]}"
            )
    return outputs


def write_or_compare(path: str, data: bytes, check_only: bool) -> bool:
    if check_only:
        try:
            with open(path, "rb") as f:
                committed = f.read()
        except OSError:
            print(f"{TAG} stale: {path} is missing or unreadable")
            return False
        if committed != data:
            print(f"{TAG} stale: {path} differs from regenerated output")
            return False
        return True
    with open(path, "wb") as f:
        f.write(data)
    print(f"{TAG} wrote {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify committed files match")
    opts = parser.parse_args()

    pin_this_tree()
    from librt.internal import WriteBuffer

    import mypy

    if not os.path.abspath(mypy.__file__).startswith(REPO_ROOT + os.sep):
        print(f"{TAG} mypy resolves outside this tree: {mypy.__file__}", file=sys.stderr)
        return 1

    manager, collected = build_corpus()
    if not collected or "Incompatible types in assignment" not in "".join(collected):
        print(
            f"{TAG} corpus build produced no assignment error; refusing to emit: {collected!r}",
            file=sys.stderr,
        )
        return 1
    corpus_errors = [e for e in collected if "class_slice" in e or "control_flow" in e]
    if corpus_errors:
        print(
            f"{TAG} real build reported errors in the checked corpus; refusing to emit: "
            f"{corpus_errors!r}",
            file=sys.stderr,
        )
        return 1
    for module_name, class_names in sorted(CORPUS_CLASSES.items()):
        module = manager.modules.get(module_name)
        if module is None:
            print(
                f"{TAG} corpus module {module_name} missing from the build; refusing to emit",
                file=sys.stderr,
            )
            return 1
        for name in class_names:
            symbol = module.names.get(name)
            node = symbol.node if symbol is not None else None
            if node is None:
                print(
                    f"{TAG} corpus class {module_name}.{name} missing from the build; "
                    "refusing to emit",
                    file=sys.stderr,
                )
                return 1
            if node.fullname != f"{module_name}.{name}":
                print(
                    f"{TAG} corpus class {module_name}.{name} did not resolve as expected "
                    f"(got {node.fullname!r}); refusing to emit",
                    file=sys.stderr,
                )
                return 1

    fixtures, golden = dump_fixtures(manager, WriteBuffer)
    fixture_bytes = (json.dumps(fixtures, indent=2, sort_keys=True) + "\n").encode()
    golden_bytes = (json.dumps(golden, indent=2, sort_keys=True) + "\n").encode()

    scratch = tempfile.mkdtemp(prefix="mypy-rs-skel-codegen-")
    expected = regen_expected(scratch)

    ok = True
    ok = write_or_compare(FIXTURE_PATH, fixture_bytes, opts.check) and ok
    ok = write_or_compare(GOLDEN_PATH, golden_bytes, opts.check) and ok
    for name, data in sorted(expected.items()):
        ok = write_or_compare(os.path.join(TESTDATA_DIR, name), data, opts.check) and ok
    if not ok:
        print(f"{TAG} FAILED: committed fixtures/expected outputs are stale")
        return 1
    print(f"{TAG} ok ({'checked' if opts.check else 'written'})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
