#!/usr/bin/env python3
"""#91 codegen: skeleton fixtures and expected-output files.

The only Python anywhere in the standalone-skeleton slice, and it runs at
fixture-creation time, never at check time. Two outputs:

1. ``crates/mypy-rs-skel/fixtures/skeleton_fixtures.json``: the
   checking-phase typeinfo read-closure the Step-0 probe measured for the
   trivial corpus (#85: 8 TypeInfos), snapshotted with exactly the read
   vocabulary the kernel's ``snapshot_type_info`` uses
   (crates/type_kernel/src/typeinfo.rs). Wire-format Type blobs are
   emitted as lowercase hex; the skeleton decodes them into
   ``TypeInfoSnapshot`` records consumed by ``is_subtype``.

2. ``crates/mypy-rs-skel/testdata/*.expected``: byte-exact expected
   stdout of real mypy on the corpus, regenerated by invoking the tree's
   own ``python -m mypy`` as a subprocess with cwd=testdata so the
   recorded paths match the differential harness invocation.

Both outputs are deterministic (sorted keys, no timestamps). ``--check``
regenerates into a scratch directory and exits 1 when the committed files
differ, for the CI freshness gate.

Usage:
  .venv/bin/python misc/skeleton_codegen.py [--check]
Prereq: the native extension scratch dirs (AGENTS.md native build
order) on PYTHONPATH, or named in MYPY_RS_EXT_DIRS (os.pathsep
list); the in-process build runs the default-on native seams and
the native parser needs the in-repo extension.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile

TAG = "[skeleton-codegen]"

# The Step-0 measured closure (#85): exactly these fullnames.
CLOSURE = [
    "builtins.object",
    "builtins.str",
    "typing.Awaitable",
    "typing.Collection",
    "typing.Container",
    "typing.Iterable",
    "typing.Reversible",
    "typing.Sequence",
]

# Primitive names the semanal subset resolves annotations through.
PRIMITIVE_NAMES = ["bool", "float", "int", "str"]

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKEL_DIR = os.path.join(REPO_ROOT, "crates", "mypy-rs-skel")
FIXTURE_PATH = os.path.join(SKEL_DIR, "fixtures", "skeleton_fixtures.json")
TESTDATA_DIR = os.path.join(SKEL_DIR, "testdata")


def pin_this_tree() -> None:
    """Worktree prelude (#1789): the shared .venv's editable finder may
    map `mypy` to another (possibly deleted) tree, and sys.path[0] is
    misc/, not the root. Pin this tree before importing mypy, and put
    the native extension dirs on sys.path: the in-process build runs
    the default-on native seams (ast_serialize et al.)."""
    if REPO_ROOT not in sys.path:
        sys.path.insert(0, REPO_ROOT)
    for finder in list(sys.meta_path):
        if "editable" in (type(finder).__module__ or "") or "editable" in repr(finder):
            sys.meta_path.remove(finder)
    for d in extension_dirs():
        if d not in sys.path:
            sys.path.insert(1, d)


def blob_hex(writer: object, buf_cls: object) -> str:
    buf = buf_cls()
    writer.write(buf)
    return bytes(buf.getvalue()).hex()


def snapshot_type_info(info: object, buf_cls: object) -> dict:
    """Mirror of ``snapshot_type_info`` (typeinfo.rs:1321-1399): the same
    attributes, the same defaults on missing/None, the same skips. Any
    divergence here is a fixture bug that the differential surfaces."""
    fullname = info.fullname
    d: dict = {}
    d["fullname"] = fullname
    d["name"] = getattr(info, "name", None) or fullname.rsplit(".", 1)[-1]
    d["is_protocol"] = bool(getattr(info, "is_protocol", False))
    d["is_enum"] = bool(getattr(info, "is_enum", False))
    enum_members = getattr(info, "enum_members", None)
    d["enum_members"] = [str(x) for x in enum_members] if enum_members else []
    d["fallback_to_any"] = bool(getattr(info, "fallback_to_any", False))
    d["meta_fallback_to_any"] = bool(getattr(info, "meta_fallback_to_any", False))
    d["is_named_tuple"] = bool(getattr(info, "is_named_tuple", False))
    d["is_newtype"] = bool(getattr(info, "is_newtype", False))
    d["has_type_var_tuple_type"] = bool(getattr(info, "has_type_var_tuple_type", False))
    d["has_param_spec_type"] = bool(getattr(info, "has_param_spec_type", False))
    d["is_abstract"] = bool(getattr(info, "is_abstract", False))
    type_vars = getattr(info, "type_vars", None)
    d["type_vars"] = [str(x) for x in type_vars] if type_vars else []
    mro = getattr(info, "mro", None)
    d["mro"] = [t.fullname for t in mro] if mro else []
    protocol_members = getattr(info, "protocol_members", None)
    d["protocol_members"] = [str(x) for x in protocol_members] if protocol_members else []
    promote = getattr(info, "_promote", None)
    d["promote_bytes"] = (
        [blob_hex(t, buf_cls) for t in promote] if isinstance(promote, list) else []
    )
    alt = getattr(info, "alt_promote", None)
    d["alt_promote_fullname"] = alt.type.fullname if alt is not None else None
    metaclass = getattr(info, "metaclass_type", "UNREADABLE")
    if metaclass == "UNREADABLE":
        d["metaclass_fullname"] = None
    elif metaclass is None:
        d["metaclass_fullname"] = ""
    else:
        d["metaclass_fullname"] = metaclass.type.fullname
    bases = getattr(info, "bases", None)
    d["bases"] = [blob_hex(b, buf_cls) for b in bases] if isinstance(bases, list) else []
    tuple_type = getattr(info, "tuple_type", None)
    d["tuple_type"] = blob_hex(tuple_type, buf_cls) if tuple_type is not None else None
    d["type_var_tuple_prefix"] = getattr(info, "type_var_tuple_prefix", None)
    d["type_var_tuple_suffix"] = getattr(info, "type_var_tuple_suffix", None)
    defn = getattr(info, "defn", None)
    defn_tvars = list(defn.type_vars) if defn is not None else []
    fallback = None
    triples = []
    upper_bounds = []
    raw_ids = []
    for tvar in defn_tvars:
        name = getattr(tvar, "name", None)
        if name is None:
            continue
        cls = type(tvar).__name__
        if cls == "TypeVarType":
            variance = int(getattr(tvar, "variance", 0))
            kind = 0
        elif cls == "ParamSpecType":
            variance, kind = 0, 1
        elif cls == "TypeVarTupleType":
            variance, kind = 0, 2
            if fallback is None:
                fallback = blob_hex(tvar.tuple_fallback, buf_cls)
        else:
            variance, kind = 0, 0
        triples.append([str(name), variance, kind])
        if kind == 0:
            bound = getattr(tvar, "upper_bound", None)
            upper_bounds.append(blob_hex(bound, buf_cls) if bound is not None else "")
        else:
            upper_bounds.append("")
        tv_id = getattr(tvar, "id", None)
        raw_ids.append(int(getattr(tv_id, "raw_id", -1)) if tv_id is not None else -1)
    d["type_vars_with_variance"] = triples
    d["type_var_upper_bounds"] = upper_bounds
    d["type_var_raw_ids"] = raw_ids
    d["type_var_tuple_fallback"] = fallback
    names = getattr(info, "names", None)
    member_info = {}
    member_definers = {}
    if names is not None:
        for name, node in names.items():
            implicit = bool(getattr(node, "implicit", False))
            has_explicit = bool(getattr(getattr(node, "node", None), "has_explicit_value", False))
            member_info[str(name)] = [implicit, has_explicit]
            inner = getattr(node, "node", None)
            kind = {"FuncDef": 0, "OverloadedFuncDef": 0, "Decorator": 1, "Var": 2}.get(
                type(inner).__name__, -1
            )
            if kind >= 0:
                definer = getattr(getattr(inner, "info", None), "fullname", "")
                member_definers[str(name)] = [kind, definer]
    d["member_info"] = member_info
    d["member_definers"] = member_definers
    return d


def build_corpus() -> tuple[object, list[str]]:
    """One in-process mypy build of the trivial corpus; returns the
    BuildManager holding the live graph the snapshots read."""
    import mypy.build
    from mypy.options import Options

    options = Options()
    options.no_incremental = True
    options.cache_dir = os.path.join(tempfile.mkdtemp(prefix="mypy-rs-skel-codegen-"), "cache")
    source = mypy.build.BuildSource(os.path.join(TESTDATA_DIR, "trivial.py"), "__main__", None)
    collected: list[str] = []
    result = mypy.build.build(
        [source], options, flush_errors=lambda path, errors, serious: collected.extend(errors)
    )
    return result.manager, collected


def dump_fixtures(manager: object, buf_cls: object) -> dict:
    records = []
    for fullname in CLOSURE:
        module_name, _, name = fullname.rpartition(".")
        symbol = manager.modules[module_name].names[name]
        info = symbol.node
        assert info.fullname == fullname, (info.fullname, fullname)
        records.append(snapshot_type_info(info, buf_cls))
    builtins_file = manager.modules["builtins"]
    primitives = {}
    for name in PRIMITIVE_NAMES:
        node = builtins_file.names[name].node
        primitives[name] = node.fullname
    return {"builtins_symbols": primitives, "typeinfos": records}


def extension_dirs() -> list[str]:
    """Extension scratch dirs for the regen subprocess. Default is the
    local trio (AGENTS.md native build order); CI overrides via
    MYPY_RS_EXT_DIRS, where the restored cache holds all three."""
    override = os.environ.get("MYPY_RS_EXT_DIRS")
    dirs = (
        override.split(os.pathsep)
        if override
        else [
            "/private/tmp/mypy-rs-local-ast",
            "/private/tmp/mypy-rs-local-resolver",
            "/private/tmp/mypy-rs-local-typekernel",
        ]
    )
    missing = [p for p in dirs if not os.path.isdir(p)]
    if missing:
        print(f"{TAG} warning: missing extension dir(s): {missing}", file=sys.stderr)
    return [p for p in dirs if os.path.isdir(p)]


def regen_expected(scratch: str) -> dict[str, bytes]:
    """Real mypy, subprocess, cwd=testdata, relative arg: the exact
    invocation shape the differential harness uses, so the recorded
    paths and bytes are stable. PYTHONPATH pins this tree plus the
    native extension scratch dirs (AGENTS.md native build order),
    because sys.path[0] for `-m` is the testdata cwd, not the repo.

    A probe subprocess resolves `mypy.__file__` under the same env and
    cwd and must land inside this tree, mirroring the in-process check
    in main(), so a bypassed PYTHONPATH pin cannot feed golden bytes
    from a foreign tree into the committed .expected files."""
    extensions = extension_dirs()
    env = os.environ.copy()
    parts = [p for p in [REPO_ROOT, *extensions] if os.path.isdir(p)]
    existing = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = os.pathsep.join(parts + ([existing] if existing else []))
    probe = subprocess.run(
        [sys.executable, "-c", "import mypy; print(mypy.__file__)"],
        cwd=TESTDATA_DIR,
        env=env,
        capture_output=True,
        text=True,
    )
    resolved = os.path.abspath(probe.stdout.strip())
    if probe.returncode != 0 or not resolved.startswith(REPO_ROOT + os.sep):
        raise RuntimeError(
            f"regen subprocess resolves mypy outside this tree: {resolved} "
            f"(returncode {probe.returncode}, stderr {probe.stderr!r})"
        )
    outputs = {}
    cache = os.path.join(scratch, "cache")
    for stem in ("trivial", "empty_control"):
        proc = subprocess.run(
            [sys.executable, "-m", "mypy", "--no-incremental", "--cache-dir", cache, f"{stem}.py"],
            cwd=TESTDATA_DIR,
            env=env,
            capture_output=True,
        )
        if proc.stderr:
            raise RuntimeError(f"mypy wrote to stderr for {stem}.py: {proc.stderr!r}")
        outputs[f"{stem}.expected"] = proc.stdout
    return outputs


def write_or_compare(path: str, data: bytes, check_only: bool) -> bool:
    if check_only:
        try:
            with open(path, "rb") as f:
                committed = f.read()
        except OSError:
            print(f"{TAG} stale: {path} is missing or unreadable")
            return False
        if committed != data:
            print(f"{TAG} stale: {path} differs from regenerated output")
            return False
        return True
    with open(path, "wb") as f:
        f.write(data)
    print(f"{TAG} wrote {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify committed files match")
    opts = parser.parse_args()

    pin_this_tree()
    from librt.internal import WriteBuffer

    import mypy

    if not os.path.abspath(mypy.__file__).startswith(REPO_ROOT + os.sep):
        print(f"{TAG} mypy resolves outside this tree: {mypy.__file__}", file=sys.stderr)
        return 1

    manager, collected = build_corpus()
    if not collected or "Incompatible types in assignment" not in "".join(collected):
        print(
            f"{TAG} corpus build produced no assignment error; refusing to emit: {collected!r}",
            file=sys.stderr,
        )
        return 1

    fixtures = dump_fixtures(manager, WriteBuffer)
    fixture_bytes = (json.dumps(fixtures, indent=2, sort_keys=True) + "\n").encode()

    scratch = tempfile.mkdtemp(prefix="mypy-rs-skel-codegen-")
    expected = regen_expected(scratch)

    ok = True
    ok = write_or_compare(FIXTURE_PATH, fixture_bytes, opts.check) and ok
    for name, data in sorted(expected.items()):
        ok = write_or_compare(os.path.join(TESTDATA_DIR, name), data, opts.check) and ok
    if not ok:
        print(f"{TAG} FAILED: committed fixtures/expected outputs are stale")
        return 1
    print(f"{TAG} ok ({'checked' if opts.check else 'written'})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
