//! Fixture loading: committed JSON (generated by `misc/skeleton_codegen.py`)
//! into a `TypeResolver` plus the primitive-name symbol map the semanal
//! pass resolves annotations through.
//!
//! The JSON schema mirrors the kernel's `snapshot_type_info` read
//! vocabulary one field per read; wire-format byte blobs travel as hex.
//! The generator is the only Python anywhere in the slice, and it runs at
//! fixture creation time, not at check time.

use std::collections::{BTreeMap, HashMap, HashSet};

use serde::Deserialize;
use type_kernel::skeleton_api::{ModuleSnapshot, TypeInfoSnapshot, TypeResolver};

/// The committed fixture file, embedded so the binary is self-contained.
const FIXTURE_JSON: &str = include_str!("../fixtures/skeleton_fixtures.json");

/// One `TypeInfoSnapshot` as generator output.
#[derive(Deserialize)]
struct TypeInfoRecord {
    fullname: String,
    name: String,
    is_protocol: bool,
    is_enum: bool,
    enum_members: Vec<String>,
    fallback_to_any: bool,
    meta_fallback_to_any: bool,
    is_named_tuple: bool,
    is_newtype: bool,
    has_type_var_tuple_type: bool,
    has_param_spec_type: bool,
    is_abstract: bool,
    type_vars: Vec<String>,
    mro: Vec<String>,
    protocol_members: Vec<String>,
    promote_bytes: Vec<String>,
    alt_promote_fullname: Option<String>,
    metaclass_fullname: Option<String>,
    bases: Vec<String>,
    tuple_type: Option<String>,
    type_var_tuple_prefix: Option<usize>,
    type_var_tuple_suffix: Option<usize>,
    type_var_tuple_fallback: Option<String>,
    type_vars_with_variance: Vec<(String, i64, i64)>,
    type_var_upper_bounds: Vec<String>,
    type_var_raw_ids: Vec<i64>,
    member_info: BTreeMap<String, (bool, bool)>,
    member_definers: BTreeMap<String, (i64, String)>,
}

/// Top-level fixture file: the checked-in snapshot of the measured
/// checking-phase read-closure (Step-0, #85) plus the primitive symbols.
#[derive(Deserialize)]
struct FixtureFile {
    typeinfos: Vec<TypeInfoRecord>,
    /// Primitive name -> fullname (`"int" -> "builtins.int"`), the exact
    /// set the semanal subset resolves annotations through.
    builtins_symbols: BTreeMap<String, String>,
}

/// Everything the driver needs from the fixtures: a populated resolver
/// and the annotation name map.
pub struct Fixtures {
    pub resolver: TypeResolver,
    pub builtins_symbols: HashMap<String, String>,
}

impl Fixtures {
    pub fn load() -> Result<Self, String> {
        let file: FixtureFile = serde_json::from_str(FIXTURE_JSON)
            .map_err(|e| format!("skeleton fixtures are unreadable: {e}"))?;
        let mut resolver = TypeResolver::new();
        for record in file.typeinfos {
            let mro = record.mro.clone();
            let has_base: HashSet<String> = mro.iter().cloned().collect();
            let snapshot = TypeInfoSnapshot {
                fullname: record.fullname,
                name: record.name,
                is_protocol: record.is_protocol,
                is_enum: record.is_enum,
                enum_members: record.enum_members,
                fallback_to_any: record.fallback_to_any,
                meta_fallback_to_any: record.meta_fallback_to_any,
                is_named_tuple: record.is_named_tuple,
                is_newtype: record.is_newtype,
                has_type_var_tuple_type: record.has_type_var_tuple_type,
                has_param_spec_type: record.has_param_spec_type,
                is_abstract: record.is_abstract,
                type_vars: record.type_vars,
                mro,
                protocol_members: record.protocol_members,
                has_base,
                promote_bytes: decode_all(&record.promote_bytes)?,
                alt_promote_fullname: record.alt_promote_fullname,
                metaclass_fullname: record.metaclass_fullname,
                bases: decode_all(&record.bases)?,
                tuple_type: decode_opt(&record.tuple_type)?,
                type_var_tuple_prefix: record.type_var_tuple_prefix,
                type_var_tuple_suffix: record.type_var_tuple_suffix,
                type_var_tuple_fallback: decode_opt(&record.type_var_tuple_fallback)?,
                type_vars_with_variance: record.type_vars_with_variance,
                type_var_upper_bounds: decode_all(&record.type_var_upper_bounds)?,
                type_var_raw_ids: record.type_var_raw_ids,
                member_info: record.member_info.into_iter().collect(),
                member_definers: record.member_definers.into_iter().collect(),
            };
            resolver.insert(snapshot.fullname.clone(), snapshot);
        }
        // No module snapshots: the corpus is one module and the semanal
        // subset keeps its own symbol records. One empty entry documents
        // the resolver's module surface without inventing module data.
        resolver.insert_module("__main__".to_string(), ModuleSnapshot::default());
        Ok(Self {
            builtins_symbols: file.builtins_symbols.into_iter().collect(),
            resolver,
        })
    }
}

fn decode_all(hex_list: &[String]) -> Result<Vec<Vec<u8>>, String> {
    hex_list
        .iter()
        .map(|h| decode_hex(h))
        .collect::<Result<Vec<_>, _>>()
}

fn decode_opt(hex: &Option<String>) -> Result<Option<Vec<u8>>, String> {
    match hex {
        Some(h) => decode_hex(h).map(Some),
        None => Ok(None),
    }
}

/// Minimal lowercase hex decode; no dependency for four lines of table.
fn decode_hex(s: &str) -> Result<Vec<u8>, String> {
    if !s.len().is_multiple_of(2) {
        return Err(format!("odd-length hex blob in fixtures: {s}"));
    }
    let bytes = s.as_bytes();
    let mut out = Vec::with_capacity(s.len() / 2);
    for pair in bytes.as_chunks::<2>().0 {
        let hi = hex_val(pair[0])?;
        let lo = hex_val(pair[1])?;
        out.push(hi << 4 | lo);
    }
    Ok(out)
}

fn hex_val(byte: u8) -> Result<u8, String> {
    match byte {
        b'0'..=b'9' => Ok(byte - b'0'),
        b'a'..=b'f' => Ok(byte - b'a' + 10),
        _ => Err(format!("non-hex byte in fixtures: {}", byte as char)),
    }
}
